
import React, { useState } from 'react';
import { ShieldAlert, BookOpen, Scale, AlertTriangle } from 'lucide-react';
import { LexGeminiService } from '../services/geminiService';

const SafeClauseAssistant: React.FC = () => {
    const [clause, setClause] = useState('');
    const [explanation, setExplanation] = useState<string | null>(null);
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);

    const handleExplain = async () => {
        if (!clause.trim()) return;

        setLoading(true);
        setError(null);
        setExplanation(null);

        try {
            const service = new LexGeminiService();
            const result = await service.explainClause(clause);
            setExplanation(result);
        } catch (err: any) {
            setError(err.message || 'Failed to analyze clause');
        } finally {
            setLoading(false);
        }
    };

    return (
        <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 w-full max-w-2xl shadow-xl">
            <div className="flex items-center gap-3 mb-6">
                <div className="p-2 bg-indigo-500/10 rounded-lg border border-indigo-500/20">
                    <BookOpen className="text-indigo-400" size={24} />
                </div>
                <div>
                    <h3 className="text-lg font-bold text-white flex items-center gap-2">
                        Safe AI Clause Assistant
                        <span className="px-2 py-0.5 rounded-full bg-emerald-500/10 border border-emerald-500/20 text-[10px] text-emerald-400 font-mono uppercase tracking-widest">
                            Legal-Safe
                        </span>
                    </h3>
                    <p className="text-xs text-slate-400">Phase 1: Educational Intent Only</p>
                </div>
            </div>

            <div className="space-y-4">
                <div>
                    <label className="text-xs font-bold text-slate-500 uppercase tracking-wider mb-2 block">
                        Contract Clause
                    </label>
                    <textarea
                        className="w-full h-32 bg-slate-950 border border-slate-800 rounded-xl p-4 text-sm text-slate-300 focus:outline-none focus:border-indigo-500/50 transition-colors"
                        placeholder="Paste legal text here..."
                        value={clause}
                        onChange={(e) => setClause(e.target.value)}
                    />
                </div>

                <button
                    onClick={handleExplain}
                    disabled={loading || !clause.trim()}
                    className="w-full py-3 bg-indigo-600 hover:bg-indigo-500 disabled:bg-slate-800 disabled:text-slate-500 text-white rounded-xl font-bold text-sm transition-all flex items-center justify-center gap-2"
                >
                    {loading ? (
                        <span className="animate-pulse">Analyzing Intent...</span>
                    ) : (
                        <>
                            <Scale size={16} />
                            Explain Intent (Safe Mode)
                        </>
                    )}
                </button>

                {error && (
                    <div className="p-4 bg-red-500/10 border border-red-500/20 rounded-xl flex items-center gap-3 text-red-400 text-xs">
                        <AlertTriangle size={16} />
                        {error}
                    </div>
                )}

                {explanation && (
                    <div className="animate-in fade-in slide-in-from-bottom-2 duration-500">
                        <div className="bg-slate-950 border border-slate-800 rounded-xl p-5 space-y-3 relative overflow-hidden">
                            <div className="absolute top-0 left-0 w-1 bg-gradient-to-b from-indigo-500 to-transparent bottom-0"></div>

                            <h4 className="text-xs font-bold text-indigo-400 uppercase tracking-widest flex items-center gap-2">
                                Plain English Explanation
                            </h4>

                            <p className="text-sm text-slate-300 leading-relaxed">
                                {explanation}
                            </p>

                            <div className="pt-3 mt-3 border-t border-slate-800/50 flex items-start gap-2">
                                <ShieldAlert className="text-amber-500 shrink-0 mt-0.5" size={14} />
                                <p className="text-[10px] text-amber-500/80 leading-tight">
                                    <strong>DISCLAIMER:</strong> This explanation is generated by AI for educational purposes only.
                                    It does not constitute legal advice. Do not rely on this for binding legal decisions without partner review.
                                </p>
                            </div>
                        </div>
                    </div>
                )}
            </div>
        </div>
    );
};

export default SafeClauseAssistant;
