import { prisma } from '../db';
import cron from 'node-cron';

export class SchedulerService {
    /**
     * Start the daily job for renewal reminders
     */
    static start() {
        // Run every day at mid-night
        cron.schedule('0 0 * * *', async () => {
            console.log('[Scheduler] Running contract renewal check...');
            await this.checkContractRenewals();
            console.log('[Scheduler] Running litigation deadline check...');
            await this.checkLitigationDeadlines();
        });
    }

    /**
     * Scan for contracts nearing renewal/expiry
     */
    static async checkContractRenewals() {
        const thirtyDaysFromNow = new Date();
        thirtyDaysFromNow.setDate(thirtyDaysFromNow.getDate() + 30);

        // Find contracts whose renewalDate is within the next 30 days and have not triggered alerts
        const contracts = await prisma.contractMetadata.findMany({
            where: {
                renewalDate: {
                    lte: thirtyDaysFromNow,
                    gte: new Date()
                },
                alertTriggered: false
            },
            include: { matter: true }
        });

        for (const contract of contracts) {
            console.log(`[Scheduler] Renewal alert for matter: ${contract.matterId}`);

            await prisma.$transaction(async (tx) => {
                // 1. Create a task for the renewal
                await tx.task.create({
                    data: {
                        title: `Contract Renewal: ${contract.matter.name}`,
                        description: `Renewal date approaching: ${contract.renewalDate?.toDateString()}`,
                        matterId: contract.matterId,
                        tenantId: contract.matter.tenantId,
                        status: 'PENDING',
                        priority: 'HIGH',
                        isAutoGenerated: true
                    }
                });

                // 2. Mark alert as triggered
                await tx.contractMetadata.update({
                    where: { id: contract.id },
                    data: { alertTriggered: true }
                });

                // 3. Log activity
                await tx.activityEntry.create({
                    data: {
                        matterId: contract.matterId,
                        tenantId: contract.matter.tenantId,
                        type: 'DEADLINE',
                        details: `Automated renewal alert triggered for contract.`
                    }
                });
            });
        }
    }

    /**
     * Scan for critical litigation deadlines
     */
    static async checkLitigationDeadlines() {
        const sevenDaysFromNow = new Date();
        sevenDaysFromNow.setDate(sevenDaysFromNow.getDate() + 7);

        const deadlines = await prisma.deadline.findMany({
            where: {
                dueDate: {
                    lte: sevenDaysFromNow,
                    gte: new Date()
                },
                isReminderSent: false,
                status: 'PENDING'
            },
            include: { matter: true }
        });

        for (const deadline of deadlines) {
            console.log(`[Scheduler] Deadline alert for matter: ${deadline.matterId}`);

            await prisma.$transaction(async (tx) => {
                await tx.task.create({
                    data: {
                        title: `CRITICAL DEADLINE: ${deadline.title}`,
                        description: `Final reminder for deadline: ${deadline.title} on ${deadline.dueDate.toDateString()}`,
                        matterId: deadline.matterId,
                        tenantId: deadline.matter.tenantId,
                        status: 'PENDING',
                        priority: 'HIGH',
                        isAutoGenerated: true
                    }
                });

                await tx.deadline.update({
                    where: { id: deadline.id },
                    data: { isReminderSent: true }
                });

                await tx.activityEntry.create({
                    data: {
                        matterId: deadline.matterId,
                        tenantId: deadline.matter.tenantId,
                        type: 'DEADLINE',
                        details: `Automated critical deadline alert triggered: ${deadline.title}`
                    }
                });
            });
        }
    }
}
