
import { prisma } from '../db';
import bcrypt from 'bcryptjs';
import { v4 as uuidv4 } from 'uuid';

interface ProvisionTenantInput {
    name: string;
    adminEmail: string;
    adminName: string;
    plan?: string;
    region?: string;
    appMode?: string;
}

interface ProvisionResult {
    tenantId: string;
    adminId: string;
    tempPassword: string;
    loginUrl: string;
}

export class TenantService {

    /**
     * Provisions a new tenant with all necessary dependencies in a single transaction.
     * 1. Create Tenant
     * 2. Create Admin User
     * 3. Create Default Roles (System Roles)
     * 4. Create Chatbot Config (Empty/Disabled)
     * 5. Create Default Branding Profile
     */
    static async provisionTenant(input: ProvisionTenantInput): Promise<ProvisionResult> {
        const { name, adminEmail, adminName, plan = 'STANDARD', region = 'GH_ACC_1', appMode = 'LAW_FIRM' } = input;

        // Generate a temporary password
        const tempPassword = Math.random().toString(36).slice(-8) + "!Aa1";
        const passwordHash = await bcrypt.hash(tempPassword, 10);
        const adminId = uuidv4();
        const tenantId = uuidv4();

        // Transaction ensures atomicity - no half-baked tenants
        await prisma.$transaction(async (tx) => {

            // 1. Create Tenant
            const tenant = await tx.tenant.create({
                data: {
                    id: tenantId,
                    name,
                    plan,
                    primaryRegion: region,
                    appMode
                }
            });

            // 2. Create Roles (TENANT_ADMIN, INTERNAL_COUNSEL)
            // We assume permissions are already seeded in the system (global/system resources)

            const adminRole = await tx.role.create({
                data: {
                    name: 'TENANT_ADMIN',
                    description: 'Full access to tenant resources',
                    isSystem: true,
                    tenantId: tenant.id,
                    permissions: {
                        connect: [
                            { id: 'manage_tenant' }, { id: 'manage_users' }, { id: 'manage_roles' },
                            { id: 'read_billing' }, { id: 'read_all_audits' }, { id: 'create_matter' }
                            // Add more default permissions as needed or fetch from a 'template'
                        ]
                    }
                }
            });

            const userRole = await tx.role.create({
                data: {
                    name: process.env.DEFAULT_USER_ROLE || 'INTERNAL_COUNSEL',
                    description: 'Standard access to matters and documents',
                    isSystem: true,
                    tenantId: tenant.id,
                    permissions: {
                        connect: [
                            { id: 'create_matter' }, { id: 'read_assigned_matter' },
                            { id: 'create_draft' }, { id: 'edit_draft' }
                        ]
                    }
                }
            });

            // 3. Create Admin User
            await tx.user.create({
                data: {
                    id: adminId,
                    email: adminEmail,
                    name: adminName,
                    passwordHash,
                    tenantId: tenant.id,
                    roleId: adminRole.id,
                    region: region, // Admin sits in primary region
                    roleSeniority: 10.0
                }
            });

            // 4. Create Chatbot Config
            await tx.chatbotConfig.create({
                data: {
                    tenantId: tenant.id,
                    botName: `${name} Assistant`,
                    welcomeMessage: `Welcome to ${name}. How can I assist you securely today?`,
                    systemInstruction: `You are the AI assistant for ${name}. Act with professional legal decorum.`,
                    channels: { webWidget: false, whatsapp: false },
                    knowledgeBaseIds: []
                }
            });

            // 5. Create Default Branding
            await tx.brandingProfile.create({
                data: {
                    tenantId: tenant.id,
                    name: 'Default Brand',
                    primaryColor: '#4F46E5',
                    secondaryColor: '#6366F1',
                    primaryFont: 'Times New Roman',
                    headerText: `${name} - Confidential`,
                    footerText: `Generated by ${name} Legal Enclave`,
                    watermarkText: 'CONFIDENTIAL'
                }
            });
        });

        // Determine Login URL (Environment specific)
        const baseUrl = process.env.PLATFORM_URL || 'http://localhost:3000';
        // In a real sub-domain app, this might be `https://${slug}.lexsovereign.com`
        // For MVP, we point them to the main login
        const loginUrl = `${baseUrl}/login?email=${encodeURIComponent(adminEmail)}`;

        return {
            tenantId,
            adminId,
            tempPassword,
            loginUrl
        };
    }

    static async getTenantDetails(tenantId: string) {
        return prisma.tenant.findUnique({
            where: { id: tenantId },
            include: {
                _count: {
                    select: { users: true, matters: true }
                }
            }
        });
    }
}
