import { prisma } from '../db';
import { EventBus } from './eventBus';

export class WorkflowService {
    /**
     * Transition a matter to a new state
     */
    static async transitionMatter(
        matterId: string,
        toStateId: string,
        userId: string,
        tenantId: string
    ) {
        return await prisma.$transaction(async (tx) => {
            // 1. Fetch Matter and current state
            const matter = await tx.matter.findUnique({
                where: { id: matterId, tenantId },
                include: { workflowState: true }
            });

            if (!matter) throw new Error('Matter not found');

            // 2. Validate Transition (if fromState exists)
            if (matter.workflowStateId) {
                const transition = await tx.workflowTransition.findFirst({
                    where: {
                        fromStateId: matter.workflowStateId,
                        toStateId: toStateId
                    }
                });

                if (!transition) {
                    throw new Error(`Invalid transition from ${matter.workflowState?.name || 'current state'} to target state`);
                }
            }

            // 3. Update Matter State
            const updatedMatter = await tx.matter.update({
                where: { id: matterId },
                data: { workflowStateId: toStateId },
                include: { workflowState: true }
            });

            // 4. Create Activity Log Entry
            await tx.activityEntry.create({
                data: {
                    matterId,
                    type: 'STATE_CHANGE',
                    actorId: userId,
                    details: `Matter transitioned to state: ${updatedMatter.workflowState?.name}`,
                    metadata: {
                        fromStateId: matter.workflowStateId,
                        toStateId: toStateId
                    }
                }
            });

            // 5. Emit Event for side-effects (outside of transaction preferred, handles via EventBus)
            EventBus.emit('STATE_CHANGED', {
                matterId,
                fromStateId: matter.workflowStateId,
                toStateId,
                userId,
                tenantId
            });

            return updatedMatter;
        });
    }

    /**
     * Create automated tasks based on state transitions
     */
    static async createAutomatedTasks(matterId: string, stateId: string, tenantId: string) {
        const state = await prisma.workflowState.findUnique({
            where: { id: stateId },
            include: { workflow: true }
        });

        if (!state || !state.canAssignTasks) return;

        // Implementation logic for auto-generating tasks defined in the workflow
        // For now, creating a placeholder 'Review' task if the state requires it
        if (state.name.toLowerCase().includes('review')) {
            await prisma.task.create({
                data: {
                    title: `Review Matter: ${matterId}`,
                    description: `Internal review required for state: ${state.name}`,
                    matterId,
                    workflowStateId: stateId,
                    isAutoGenerated: true,
                    priority: 'HIGH',
                    status: 'PENDING'
                }
            });
        }
    }
}

// Subscribe to state changes for automation
EventBus.on('STATE_CHANGED', async (data) => {
    try {
        await WorkflowService.createAutomatedTasks(data.matterId, data.toStateId, data.tenantId);
    } catch (error) {
        console.error('Error in automated task generation:', error);
    }
});

// Subscribe to Quorum success for auto-transitions
EventBus.on('QUORUM_MET', async (data) => {
    try {
        // 1. Fetch current matter state
        const matter = await prisma.matter.findUnique({
            where: { id: data.matterId },
            include: { workflowState: { include: { outgoingTransitions: true } } }
        });

        if (!matter || !matter.workflowState) return;

        // 2. Automate transition to the next logical state if one is defined
        const nextTransition = matter.workflowState.outgoingTransitions[0];
        if (nextTransition) {
            await WorkflowService.transitionMatter(
                data.matterId,
                nextTransition.toStateId,
                'SYSTEM_BOT', // Indicates system-triggered change
                matter.tenantId
            );
        }
    } catch (error) {
        console.error('Error in auto-transition on quorum:', error);
    }
});
